language: bash
services: docker
lefore_install:
  - cd api/
  - echo "estamos no docker folder"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login -- username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: scrypt
  scrypt:
    docker push robertoangelodasilvaramos/mysql-rest-spring-boot;
    docker robertoangelodasilvaramos/api
  on:
    branch: master
notifications:
  email: false     
