version: "3.4"
services:
  db:
    image: robertoangelodasilvaramos/mysql-rest-spring-boot
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile:  Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_spring_boot
    ports:
      - "3308:3306"
    networks:
      - roberto-network
  api:
    image: robertoangelodasilvaramos/api
    restart: always
    build: ./api
    working_dir: /api
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./api:/api
      - ~/.m2:/root/.m2
    ports:
      - "9090:9090"
    command: mvn clean package spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - roberto-network
networks:
    roberto-network:
        driver: bridge